### ISSUE TITLE
Runway update (seems to) causes: foreach() argument must be of type array|object, null given error

### ISSUE THREAD

**Issue by itsmesaskovic** [duncanmcclean/runway#322]
### Description

After installing the latest version of Runway and running an `php artisan` command after publishing the Eloquent Driver config I get the following error: 

```
[2023-09-07 07:02:38] local.ERROR: foreach() argument must be of type array|object, null given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, null given at D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php:587)
[stacktrace]
#0 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'foreach() argum...', 'D:\\\\dev\\\\xampp\\\\no...', 587)
#1 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php(587): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'foreach() argum...', 'D:\\\\dev\\\\xampp\\\\no...', 587)
#2 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(825): Illuminate\\Support\\Arr::mapWithKeys(Array, Object(Closure))
#3 D:\\dev\\xampp\\nofam-web-peak\\vendor\\doublethreedigital\\runway\\src\\Runway.php(18): Illuminate\\Support\\Collection->mapWithKeys(Object(Closure))
#4 D:\\dev\\xampp\\nofam-web-peak\\vendor\\doublethreedigital\\runway\\src\\ServiceProvider.php(77): DoubleThreeDigital\\Runway\\Runway::discoverResources()
#5 D:\\dev\\xampp\\nofam-web-peak\\vendor\\statamic\\cms\\src\\Statamic.php(352): DoubleThreeDigital\\Runway\\ServiceProvider->DoubleThreeDigital\\Runway\\{closure}()
#6 D:\\dev\\xampp\\nofam-web-peak\\vendor\\statamic\\cms\\src\\Providers\\AppServiceProvider.php(29): Statamic\\Statamic::runBootedCallbacks()
#7 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1053): Statamic\\Providers\\AppServiceProvider->Statamic\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application))
#8 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(996): Illuminate\\Foundation\\Application->fireAppCallbacks(Array)
#9 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#10 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(261): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#11 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(447): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#12 D:\\dev\\xampp\\nofam-web-peak\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#13 D:\\dev\\xampp\\nofam-web-peak\\artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} 
```

Can this be related to the changes made in the last Runway version?

### Steps to reproduce

1. Have a SimpleCommerce instal with Runway
2. composer require statamic/eloquent-driver
3. php artisan vendor:publish --tag="statamic-eloquent-config"
4.  php artisan vendor:publish --provider="Statamic\Eloquent\ServiceProvider" --tag=migrations

This last command fails with the presented error. PHP artisan serve also fails with the same error.
Removing the eloquent config "solves" the issue.

### Environment

```
Environment
Application Name: Nofam
Laravel Version: 10.22.0
PHP Version: 8.2.9
Composer Version: 2.4.2
Environment: local
Debug Mode: OFF
URL: 127.0.0.1:8000/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Package shipping method
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 7
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.20.0 PRO

Statamic Addons
doublethreedigital/runway: 5.2.1
doublethreedigital/simple-commerce: 5.3.7
joetannenbaum/antlers-stack-tags: 0.1.0
mitydigital/sitemapamic: 2.3.8
roorda-ict/statamic-entries-export: 2.1.0
statamic/eloquent-driver: 2.6.2
stoffelio/statamic-turnstile: 1.1.0

Statamic Eloquent Driver
Asset Containers: file
Assets: file
Blueprints: file
Collection Trees: file
Collections: file
Entries: file
Forms: file
Global Sets: file
Global Variables: file
Navigation Trees: file
Navigations: file
Revisions: file
Taxonomies: file
Terms: file
```

**Comment by duncanmcclean** [comment]
I'm guessing your Runway config looks the same as it did in the previous issue?
